# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [2]:
# import numpy and pandas
import numpy as np
import pandas as pd

# Challenge 1 - Independent Sample T-tests

In this challenge, we will be using the Pokemon dataset. Before applying statistical methods to this data, let's first examine the data.

To load the data, run the code below.

In [5]:
# Run this code:

pokemon = pd.read_csv('pokemon.csv')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Let's start off by looking at the `head` function in the cell below.

In [7]:
# Your code here:
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

The first thing we would like to do is compare the legendary Pokemon to the regular Pokemon. To do this, we should examine the data further. What is the count of legendary vs. non legendary Pokemons?

In [8]:
# Your code here:
pokemon["Legendary"].value_counts()

False    735
True      65
Name: Legendary, dtype: int64

Compute the mean and standard deviation of the total points for both legendary and non-legendary Pokemon.

In [9]:
# Your code here:
pokemon.groupby("Legendary")["Total"].std()

Legendary
False    106.760417
True      60.937389
Name: Total, dtype: float64

The computation of the mean might give us a clue regarding how the statistical test may turn out; However, it certainly does not prove whether there is a significant difference between the two groups.

In the cell below, use the `ttest_ind` function in `scipy.stats` to compare the the total points for legendary and non-legendary Pokemon. Since we do not have any information about the population, assume the variances are not equal.

In [10]:
# Your code here:
pokemon.groupby("Legendary")["Total"].mean()

Legendary
False    417.213605
True     637.384615
Name: Total, dtype: float64

What do you conclude from this test? Write your conclusions below.

In [13]:
# Your conclusions here:
s_legendary = np.random.normal(637.384615, 60.937389, 1000)
s_non_legendary = np.random.normal(417.213605, 106.760417, 1000)

s_legendary

# Legandery is the mean and non legendary is the STD.

array([582.63816951, 604.62613659, 709.22619347, 643.3463394 ,
       659.7992153 , 684.28681266, 791.99810007, 654.37131278,
       669.87002522, 787.54735205, 631.18139009, 724.92512666,
       547.6568534 , 633.95654708, 620.60971176, 718.731773  ,
       595.73730927, 610.8364199 , 656.19290912, 647.27413963,
       605.95970928, 696.96715948, 637.01208675, 641.19638721,
       723.78321957, 582.6738668 , 585.15254385, 633.88921256,
       743.55556563, 615.84564284, 718.36508001, 722.55427965,
       687.95742304, 673.38014135, 648.10735534, 629.74807888,
       577.28126485, 651.85052529, 594.76421877, 659.25595838,
       683.74055614, 622.2413803 , 677.30788337, 638.01694747,
       562.94952999, 525.93289825, 462.77620822, 567.22140557,
       559.01273705, 583.19668983, 715.34242174, 685.34627904,
       576.3328423 , 617.93567774, 628.03231722, 529.95974334,
       662.52548673, 660.76802357, 609.21492252, 554.4386385 ,
       736.82597144, 536.1612813 , 598.86526897, 608.6523076 ,
       527.27982928, 627.10629099, 668.64521794, 688.4854344 ,
       545.60507625, 732.02148744, 682.3790403 , 648.34201734,
       636.53718348, 611.71793911, 568.09988324, 730.09260889,
       650.14462334, 610.43561631, 684.63301525, 721.19225979,
       636.34078422, 637.28833093, 561.4047196 , 515.27877352,
       586.435739  , 680.08543638, 685.29657722, 624.20948366,
       719.61035323, 659.04868978, 774.1944187 , 626.72838795,
       620.03596869, 669.7948752 , 570.57482885, 682.7863565 ,
       676.598213  , 639.48301417, 651.01979602, 654.65893191,
       666.63407891, 673.20602087, 614.10359686, 639.35599211,
       770.86651382, 635.83179623, 562.8516021 , 634.54816104,
       690.60735441, 674.20921424, 663.43089086, 556.19356022,
       599.73742808, 558.3673339 , 642.6516813 , 636.5428539 ,
       709.30811543, 679.34801026, 690.72358937, 733.72460825,
       555.1595101 , 632.52908002, 497.07183517, 621.85324049,
       652.91392558, 720.48109586, 579.43848062, 666.20054638,
       590.279744  , 597.98229208, 714.67416246, 628.96517178,
       583.99162323, 710.29104592, 540.67033272, 699.1910275 ,
       641.23113811, 596.45932962, 598.70703362, 527.45983245,
       547.64966294, 550.5669138 , 607.3681164 , 591.96122689,
       644.19967   , 651.25466696, 542.24221047, 634.74487698,
       577.55906207, 660.94176881, 630.30001275, 670.19512124,
       647.32701907, 593.5421251 , 630.35983057, 602.0278392 ,
       601.9606711 , 637.30231735, 639.14507154, 659.7868945 ,
       574.36269897, 661.44457387, 520.61027165, 767.17315536,
       626.24705183, 660.86792515, 589.68197753, 598.30788903,
       641.11232303, 616.62738208, 678.1247448 , 630.19053843,
       574.41593779, 631.88842311, 706.8329902 , 701.73114178,
       656.67483958, 568.31697254, 763.11836688, 623.73396648,
       753.31235173, 644.3880395 , 653.10809972, 765.25218767,
       553.3937924 , 740.3711744 , 548.6047918 , 693.38033957,
       701.68669606, 619.00793157, 552.75826351, 731.20223199,
       737.63721434, 679.79034918, 628.33600962, 596.00884011,
       720.85015751, 656.06943947, 659.71558288, 611.11132711,
       605.61575158, 673.56883239, 568.91887316, 674.85448028,
       586.99150562, 631.54748927, 672.76132193, 555.2147792 ,
       704.53835904, 712.71502434, 720.31616051, 729.56056671,
       667.23414797, 662.77029713, 554.46705982, 635.22251281,
       753.74327471, 675.66483241, 687.25489186, 730.38732086,
       686.59562279, 727.95257313, 616.76245902, 673.29867505,
       660.36629372, 682.28697016, 511.5039432 , 672.92443931,
       523.9474231 , 640.55558357, 618.69021831, 519.26332302,
       562.01691262, 681.83673965, 645.53615399, 624.00960195,
       522.64333561, 614.74026046, 631.50796856, 646.43112318,
       580.71449084, 591.95840549, 618.21211424, 522.64458608,
       664.08712549, 643.43661829, 620.68313606, 612.53836764,
       666.56451897, 667.39656049, 653.76992543, 575.71110264,
       663.53554829, 598.4291594 , 620.4790773 , 736.05525159,
       600.99747157, 652.33763565, 584.71655149, 770.56742998,
       650.31973779, 624.87883114, 607.02647083, 643.98201927,
       602.35523838, 701.36199478, 693.71810471, 638.75773278,
       743.45289791, 691.17571271, 711.57334473, 678.13234103,
       749.78989167, 602.48347294, 599.35277852, 673.08717657,
       526.42057253, 595.69596752, 632.66007947, 639.99053113,
       695.1046783 , 599.22015139, 831.6953006 , 551.27050473,
       614.06281333, 551.41946977, 637.75016511, 662.59729327,
       613.38576874, 718.66583216, 724.04999499, 626.46709829,
       639.90343218, 737.9180929 , 663.9536415 , 686.20947301,
       660.34643908, 621.41048883, 555.05255333, 660.08793079,
       672.13321435, 648.06528748, 610.0044593 , 673.21367453,
       608.10085444, 643.480537  , 605.80940543, 445.22192958,
       679.95416458, 615.77599093, 602.90361139, 507.83403101,
       680.91950206, 530.01220303, 608.75207709, 780.1983497 ,
       691.83335797, 635.50599494, 545.04167269, 629.14971299,
       510.91113883, 643.49492291, 617.17410744, 645.86129376,
       600.53806613, 647.78937874, 717.78658255, 648.13953066,
       563.10679449, 655.61969199, 615.07594026, 640.0530436 ,
       647.3422037 , 659.0620013 , 730.50158508, 703.33069884,
       543.23489797, 754.1017609 , 698.79815263, 633.18253303,
       597.03732025, 592.10859911, 641.32842202, 679.0900562 ,
       651.16859345, 599.04998232, 661.54776027, 780.45553847,
       712.0269765 , 642.37509574, 534.29000628, 695.21522667,
       557.82460343, 648.5050272 , 600.54367199, 528.34294028,
       561.46665479, 695.21080888, 641.79127607, 610.63413905,
       664.78737868, 689.78900188, 658.50847465, 540.7368129 ,
       680.52152183, 537.72652976, 619.6523014 , 605.51137489,
       660.38443026, 597.71880142, 662.15298834, 650.61776327,
       511.65658072, 479.82607648, 605.69674977, 595.14988167,
       509.17435121, 666.31168612, 613.56489051, 490.40427059,
       695.89750945, 638.96302421, 641.20692528, 743.63246934,
       532.02464011, 543.73834703, 709.81268047, 567.73471781,
       675.88559356, 728.11943953, 629.37523735, 648.0859515 ,
       584.16202695, 625.1195374 , 704.64537017, 632.00403604,
       631.19351027, 669.13016967, 705.65594543, 589.51365568,
       584.27966572, 748.82549834, 754.33723206, 600.76994845,
       635.20218784, 579.11580373, 667.66439379, 660.64583944,
       690.39173467, 652.54081252, 616.34416668, 662.16087451,
       620.89220313, 660.11720271, 591.35179818, 611.34949443,
       564.23399119, 610.67681101, 634.33200979, 593.19178051,
       700.18447936, 614.03252844, 588.26814213, 615.05726047,
       594.24422711, 670.67839991, 589.9090875 , 649.00192437,
       605.99221897, 594.71893643, 678.32885705, 745.40749147,
       549.29257164, 698.12128841, 677.78076503, 742.35873682,
       761.57265901, 657.25620917, 638.90164146, 668.01820247,
       619.57381603, 643.40555865, 684.29295426, 750.60257288,
       506.07645185, 595.25314657, 508.75492856, 576.36916151,
       523.28651731, 624.57014011, 643.97414942, 656.43491805,
       707.54689337, 457.87948143, 546.41902621, 718.23548249,
       608.22570388, 638.29866467, 659.18570228, 698.99143563,
       621.8032448 , 658.44859314, 640.234565  , 757.66735325,
       683.6572435 , 611.10318322, 602.03561253, 666.13263923,
       570.70816218, 684.62526169, 675.48448905, 683.35774663,
       583.55282065, 628.65434366, 719.36790502, 639.85014453,
       699.01235067, 660.15656603, 688.96296048, 676.08898564,
       577.49632843, 736.75379664, 709.02890739, 495.56253692,
       606.5312335 , 681.10819156, 708.32703078, 751.4776202 ,
       523.70412506, 587.32217826, 635.59768642, 682.15961101,
       651.26739758, 725.09045337, 678.59774923, 761.29971514,
       625.59996943, 584.04857846, 576.9618628 , 630.06502063,
       557.04942238, 674.55444005, 659.90376413, 623.5297406 ,
       660.20867854, 715.41321644, 629.82782969, 524.06560393,
       690.01943788, 642.70786075, 611.66281382, 597.27990256,
       668.8587087 , 729.7017334 , 615.88436075, 631.44523643,
       526.2444045 , 648.28783734, 636.30205906, 574.4998739 ,
       674.96856987, 594.94712898, 667.0010741 , 617.73496137,
       713.16749509, 653.53673953, 667.02688511, 642.00065661,
       561.50654486, 683.68052673, 538.40698648, 681.55880494,
       714.18319158, 575.78039074, 656.07760958, 714.05325866,
       652.76627792, 547.08395634, 639.89170197, 618.85255922,
       564.04524315, 571.35261755, 589.43159516, 626.44559284,
       550.62952806, 594.7107325 , 681.14511114, 678.76267707,
       648.65077675, 608.24744994, 692.29689169, 637.3962491 ,
       782.84530215, 657.96240623, 671.54656662, 664.76165729,
       662.38060638, 616.55514022, 689.8431497 , 630.22460055,
       648.74741069, 665.19638345, 684.17201614, 646.39856315,
       675.95752282, 642.32413205, 702.63658808, 669.16468666,
       683.77352955, 670.81706514, 726.22942638, 668.26315405,
       633.86794692, 634.76109387, 620.22219117, 600.26227756,
       661.79416217, 547.58218143, 580.42989723, 690.77780017,
       646.39054673, 645.5500268 , 696.00051532, 600.73009205,
       722.82830999, 594.77046013, 581.99195022, 659.63418446,
       656.33998779, 530.93708557, 614.05871522, 605.5643822 ,
       613.49410477, 612.59039028, 536.7522034 , 578.12972158,
       584.01561208, 647.85819202, 592.4690174 , 721.45400263,
       686.79857561, 601.25152327, 643.84634495, 638.72851807,
       622.99593276, 689.87628084, 533.5204848 , 508.72797032,
       615.05774035, 635.33352732, 615.41149921, 697.63234739,
       586.42099516, 657.01233923, 758.24369833, 588.9616592 ,
       628.26123478, 681.05355804, 630.22538858, 591.25045408,
       499.10189555, 675.78261427, 553.62432036, 640.48530752,
       747.1099013 , 674.88423342, 579.10370397, 679.60881512,
       695.82011244, 565.49964944, 597.17728739, 695.23982766,
       711.13660336, 602.52515203, 704.48337772, 604.96683288,
       679.17765328, 645.72516506, 706.84011544, 638.11191535,
       646.34762247, 633.71815343, 604.2301049 , 643.87659982,
       628.76915359, 723.67412293, 598.34234876, 556.79424479,
       656.11903389, 661.07468789, 641.38538526, 644.95545253,
       589.72914597, 626.04344576, 646.26685983, 780.96174218,
       651.65643908, 660.87817909, 707.6897476 , 591.14291011,
       649.23417974, 625.60784329, 606.4979421 , 582.95918828,
       713.03745448, 660.08564449, 700.29822972, 530.24675626,
       578.55990121, 594.97994967, 734.21296077, 653.22971753,
       596.55611904, 594.14446474, 663.36914728, 648.81326329,
       674.76125383, 701.56061258, 627.49888463, 607.97061944,
       590.84681883, 673.83415548, 545.42808799, 650.00869354,
       612.66234323, 603.65059262, 620.9141952 , 641.80338175,
       732.51045976, 622.43683913, 621.82943119, 679.20138982,
       622.29282236, 678.87346035, 665.86792618, 546.88301224,
       559.02642181, 636.46971196, 650.96976591, 665.67288786,
       624.75972965, 722.04360085, 630.64161763, 591.74737892,
       660.34411628, 673.05823534, 676.23799655, 605.47208136,
       698.4224173 , 608.77066072, 568.41805454, 590.64821853,
       629.40352463, 642.5385905 , 525.27373022, 625.20763438,
       679.44633975, 644.37253815, 579.62762031, 558.77683053,
       537.12121377, 584.70634512, 550.1892642 , 762.63177061,
       606.28643621, 574.06162248, 610.0884672 , 723.21992899,
       635.01281486, 684.56891183, 559.49380287, 567.82000505,
       774.08311743, 605.58751309, 601.07511847, 687.46892762,
       645.10223357, 611.56499916, 631.47262852, 698.12638599,
       724.94617819, 612.16399359, 765.34766962, 730.00423416,
       680.81146235, 584.83738352, 726.52772059, 662.94906577,
       754.03929438, 530.99906775, 679.05401879, 704.2291418 ,
       557.34880239, 652.37448413, 697.66973676, 620.09854155,
       694.59188189, 666.89863149, 594.92393046, 657.41036161,
       689.07956096, 650.39289274, 580.38333787, 658.29936375,
       680.54467259, 560.27527407, 652.08758248, 656.14942484,
       458.08656433, 567.37187088, 536.58137313, 614.07153489,
       732.68612405, 625.10140325, 704.75086904, 665.45892454,
       596.87852692, 599.58077563, 667.04682088, 637.55839441,
       484.425197  , 743.51361516, 573.57329869, 606.32452677,
       686.60760437, 613.10513404, 539.43831714, 633.75381612,
       587.81978837, 665.70036956, 572.07695049, 382.82832926,
       641.18386476, 697.40236059, 659.06825232, 620.03836193,
       476.8884018 , 572.59154578, 654.66837148, 699.28955613,
       656.55479092, 517.53761676, 622.78549852, 529.13438728,
       574.13484312, 546.19457123, 542.79716323, 623.75517404,
       649.55160284, 553.47651827, 502.45407184, 642.06056273,
       585.82692696, 630.48370702, 710.82912359, 643.23305907,
       570.72976291, 716.55256101, 684.9377596 , 758.41083617,
       507.09582441, 709.55824952, 663.83577356, 711.74167341,
       710.65454312, 560.12430793, 644.73484028, 592.39807157,
       619.95046766, 593.07994955, 492.63896143, 614.47664486,
       616.20842374, 605.37623322, 569.85196121, 611.73855786,
       670.09497684, 664.07809542, 566.82819427, 698.94391868,
       600.59362537, 610.96150725, 545.39375551, 710.25996466,
       574.17388702, 592.485444  , 542.96639458, 575.3292219 ,
       695.73541103, 668.4529408 , 631.00943488, 575.00450309,
       552.03889159, 647.36677945, 624.02107669, 682.25550657,
       682.99772843, 605.3139557 , 680.73052789, 723.2099157 ,
       713.43414277, 558.26405552, 641.30834877, 700.18473973,
       588.67826644, 672.6234451 , 619.25798314, 765.16726631,
       670.56496507, 653.13073794, 652.8596227 , 734.06841859,
       610.76194585, 585.84406765, 677.45739986, 741.64028971,
       713.72391174, 573.56445522, 606.81480245, 568.23393492,
       575.02922874, 729.24165739, 536.93137562, 680.32889631,
       556.74719634, 601.23770413, 644.12437888, 547.74787615,
       612.43824743, 643.80157804, 660.93804139, 731.151927  ,
       668.75934355, 739.7996418 , 555.20471122, 623.39382924,
       681.21912866, 581.40908677, 568.86132071, 524.89897436,
       715.10508628, 633.65674227, 663.27782453, 544.99743616,
       552.62352184, 672.20579921, 666.64042157, 615.42668146,
       624.11892249, 571.02958891, 691.16288404, 570.73041938,
       566.02640779, 584.53389036, 673.53019303, 554.09513303,
       587.39076909, 692.47659117, 484.72437967, 587.22584229,
       766.41483282, 615.25623197, 663.08168278, 517.53545738,
       655.87648428, 577.83129405, 643.44065789, 566.05400407,
       698.77679966, 679.16368025, 802.81417   , 717.86173984,
       638.10826543, 608.14860875, 604.77239995, 511.62234177,
       599.54434805, 648.37419715, 659.65488801, 511.0501415 ,
       588.57934926, 593.34507514, 772.5535532 , 720.33651449,
       517.98155338, 676.16332442, 566.85128917, 584.24682617,
       553.37232112, 692.338414  , 563.92984096, 729.27767592,
       825.73943978, 790.96964688, 619.50191779, 574.29510444,
       523.43590119, 660.3549167 , 603.40797547, 573.08066014,
       781.79025058, 733.14188058, 653.899959  , 624.01023636,
       714.83992789, 591.52867419, 618.15178526, 585.12667908,
       692.85345844, 638.01083183, 624.29799268, 605.25611803,
       599.57553291, 647.15637788, 664.25289713, 595.88242571,
       546.59492455, 510.14490553, 689.12886803, 608.89596736,
       592.22840058, 600.0420019 , 551.04076283, 610.31684523,
       616.41371371, 693.87285304, 663.09321245, 642.39608513,
       609.54505444, 764.32613038, 564.56309036, 577.30655302,
       604.43056086, 591.14967291, 537.85624603, 568.56785347,
       529.70999089, 563.87576289, 581.46210965, 676.34785942])

In [14]:
s_non_legendary

array([358.6244162 , 302.77010777, 338.6828508 , 350.24388739,
       409.46287721, 587.68374328, 299.09585003, 294.85302553,
       447.42165214, 455.44630583, 307.05639682, 555.4203971 ,
       530.27757196, 483.40922718, 237.63273611, 304.55868872,
       435.11883137, 495.5531776 , 277.40912658, 409.03643089,
       415.939269  , 214.46406409, 476.23144992, 469.47163979,
       377.54724503, 465.14533484, 420.71278568, 383.17527599,
       388.47231554, 401.37413151, 496.91532332, 551.46840867,
       521.24739613, 326.68119502, 689.48363303, 448.55959725,
       452.88765155, 424.14441632, 365.31013697, 406.75414877,
       538.35877381, 447.8363534 , 352.88428557, 539.77850607,
       347.62821905, 315.06114493, 584.37503141, 460.07406384,
       364.84620965, 288.61646546, 470.76082239, 442.73115467,
       349.52160181, 387.94789491, 448.67213049, 398.47450513,
       369.93075264, 425.51080762, 451.63795542, 329.51755828,
       496.39399986, 347.91172672, 448.51630815, 373.91546091,
       230.60988017, 328.63493347, 490.30884648, 522.34945179,
       356.483059  , 378.258586  , 413.31204618, 503.81331586,
       597.02819582, 509.85399781, 380.96443586, 430.51510718,
       370.27760938, 242.80964741, 282.79923752, 360.87293642,
       386.90443734, 444.02539902, 429.54815805, 572.96060682,
       408.75344951, 442.83843903, 522.60154314, 493.20158191,
       581.71203518, 477.92467739, 384.37891705, 407.36660191,
       629.33988351, 412.75916773, 462.45524959, 356.20958958,
       372.65680746, 415.78380341, 519.51826694, 274.84143687,
       603.61549742, 420.3408349 , 479.22130486, 385.62174624,
       468.57376146, 485.4506411 ,  80.65412228, 474.37046731,
       534.64558102, 302.8758152 , 390.49588793, 440.05102795,
       326.69870989, 349.09485537, 389.2256478 , 581.23179291,
       761.75773916, 264.65638176, 397.350237  , 496.41212116,
       198.88551478, 365.97850661, 406.48368142, 546.78789985,
       252.83653242, 352.18945149, 293.2405189 , 479.62256984,
       336.11252556, 528.39957929, 297.02437442, 489.32430343,
       299.60801931, 407.62949163, 417.25382569, 579.33118599,
       342.72052757, 417.9174126 , 495.48058351, 595.20572047,
       326.48647037, 372.82087137, 396.47129151, 521.77124331,
       279.945237  , 309.79819116, 271.01719636, 391.10787714,
       522.62506588, 433.45604203, 415.00188037, 459.7950904 ,
       499.10209514, 369.2888498 , 435.17809287, 222.79633971,
       274.30145336, 453.82237438, 452.31877835, 320.90454069,
       432.74101297, 316.74688181, 626.75237858, 432.5928304 ,
       536.5020545 , 441.22543744, 466.45082621, 371.42725625,
       393.18093358, 117.01417545, 369.26285793, 356.90791727,
       527.48259192, 234.09121449, 362.03449772, 452.18109335,
       453.46821357, 311.84724265, 223.34979639, 416.47709301,
       449.49974121, 391.2490292 , 184.48066435, 434.36681023,
       360.37526597, 339.29378829, 458.99353491, 422.32298849,
       587.12454814, 373.18246805, 551.4284945 , 377.4302698 ,
       386.96819605, 447.4097191 , 498.30063747, 294.10228338,
       564.56737572, 503.90113517, 591.41994476, 366.52035166,
       524.1926695 , 597.23867065, 366.13721629, 438.36242931,
       418.58903955, 572.81529565, 572.10992235, 550.48913139,
       110.70988905, 414.94810876, 390.9234446 , 500.86517887,
       325.20763657, 332.95989609, 334.37803977, 484.68145089,
       480.49902571, 390.57178434, 337.90397117, 210.8775169 ,
       202.8066689 , 418.64825406, 268.63405615, 184.62726877,
       438.27890103, 430.05954545, 725.81842656, 447.69357834,
       499.41216044, 426.03837154, 576.64544129, 511.85077139,
       491.23518722, 471.80509473, 184.71921265, 478.17536411,
       591.70628384, 341.9345004 , 447.11512188, 396.599102  ,
       430.29414798, 314.6491629 , 502.9532159 , 436.79258067,
       379.76644429, 541.20188337, 510.92974613, 451.65895669,
       385.00163728, 235.15895807, 426.54963995, 437.07940817,
       483.10918132, 433.06429861, 420.9698424 , 369.13584714,
       422.76667231, 593.03708391, 480.93847468, 354.01430036,
       544.7936952 , 124.84653713, 657.5824536 , 491.68163683,
       290.64732893, 533.43241606, 377.02512845, 345.87668914,
       325.50855109, 433.52083465, 374.4650339 , 438.25687272,
       268.71153115, 266.12885062, 462.06354499, 185.95536311,
       527.88598275, 470.3981988 , 294.55040111, 529.1815815 ,
       378.69451633, 498.7126352 , 409.18771909, 578.37379263,
       346.68783674, 457.31473247, 404.45826892, 299.15396311,
       458.37907479, 441.75201784, 515.83261088, 456.91019116,
       458.39834556, 190.57007628, 399.17307038, 420.38610182,
       531.27432238, 506.33621086, 334.21914247, 338.36694164,
       400.67965159, 275.46679584, 263.66176414, 307.48275982,
       390.41948542, 331.6660042 , 462.15628449, 544.78300831,
       413.24509299, 450.09935555, 470.67088503, 378.62120941,
       306.98166561, 550.13472217, 366.5199091 , 482.46835906,
       438.31827944, 273.62880945, 482.61565713, 579.78156449,
       409.99471551, 377.31358063, 533.0776619 , 481.01394461,
       559.07261931, 545.98797711, 350.07524392, 531.67143918,
       516.75640922, 351.55094578, 250.37877713, 441.59056843,
       408.37428913, 288.79773774, 580.09290063, 370.0659042 ,
       364.09218444, 446.01814955, 431.80248871, 452.5711404 ,
       427.0086634 , 392.29729006, 378.48250045, 457.14732659,
       646.46578489, 530.98512362, 415.531609  , 504.68080858,
       286.13847709, 314.63210356, 352.84749926, 405.90924792,
       321.54436448, 306.06985661, 457.04329783, 435.92456176,
       259.58605717, 376.88569827, 566.25168514, 421.84505107,
       451.08256597, 373.27865973, 489.99612396, 630.06797606,
       455.81631268, 520.99143613, 283.03163377, 393.07159292,
       493.92961677, 402.2506867 , 580.15194411, 442.42396196,
       499.46253352, 261.45746629, 368.99921257, 425.67700364,
       408.66303421, 411.3261843 , 402.8147664 , 611.94977349,
        63.20947963, 396.48636316, 441.92993363, 430.87036723,
       351.38755702, 451.3143733 , 569.19181963, 299.11726869,
       500.36515944, 402.70196947, 315.79962154, 543.95839999,
       527.66920465, 434.20141172, 322.54191738, 283.8231799 ,
       435.27877631, 556.84973338, 365.21839491, 527.44644847,
       320.48182339, 532.47301318, 458.56802107, 337.79713821,
       266.3631969 , 362.13344313, 435.79066576, 283.15839399,
       357.21596827, 344.10080976, 325.81070287, 475.40347923,
       351.24589057, 503.13021041, 546.582053  , 319.6184761 ,
       232.8041586 , 296.57664714, 726.75836552, 504.90939364,
       311.69668798, 348.04548785, 363.71703849, 300.15944698,
       366.72138689, 451.16869175, 451.28060089, 408.51720001,
       332.87170127, 239.08891869, 428.93156117, 336.15149472,
       501.56780388, 485.98223843, 403.72475189, 332.45778804,
       366.88242729, 509.89128029, 381.38419789, 179.1273913 ,
       355.95388597, 378.40834119, 300.96953949, 512.32971089,
       429.56554749, 383.30900224, 437.36027854, 502.69849649,
       173.85407215, 386.75917846, 316.00968904, 472.17366291,
       551.7023336 , 496.93104313, 518.85434319, 308.8631191 ,
       305.98985551, 279.79042172, 339.78052424, 387.32066484,
       536.39370168, 432.21630064, 414.70810092, 541.18444977,
       374.85445484, 340.08725496, 463.49955462, 486.2181109 ,
       496.24641977, 449.44335387, 513.40378596, 411.39834796,
       510.34318611, 374.14504635, 214.17644285, 474.42127096,
       531.12250056, 440.41947026, 423.78080112, 374.67395382,
       408.56060093, 554.81535356, 515.85665004, 508.0983391 ,
       413.44357234, 498.6397641 , 313.02738541, 530.68849159,
       529.34588681, 398.26445901, 291.14547858, 251.47790104,
       449.9155086 , 414.88144554, 505.99712029, 428.1599842 ,
       342.07961359, 321.49004082, 334.2355473 , 526.44084152,
       619.11415437, 408.12425824, 463.87700946, 497.12917808,
       377.71643   , 507.30872405, 399.76217442, 364.20066539,
       496.68029771, 400.47175758, 385.27920795, 377.53382272,
       379.35454938, 476.03828215, 338.81828521, 522.48329245,
       279.58980267, 288.7500586 , 371.36905965, 437.77732973,
       534.24582359, 610.52702122, 215.87380248, 399.3940229 ,
       634.13370602, 547.61926211, 349.90843783, 261.99377694,
       235.76280945, 687.88938249, 330.93416823, 410.16991405,
       496.79443049, 499.20845359, 357.32704439, 385.4811564 ,
       498.68008762, 497.74625898, 333.97813887, 399.77003873,
       409.31933043, 284.85919888, 447.83361668, 520.54673369,
       632.66859195, 415.73849433, 394.78802483, 454.45136385,
       574.60208303, 513.96025118, 137.6988304 , 316.95155745,
       444.71685821, 669.62191505, 249.25330967, 418.16843302,
       631.19032007, 324.35841259, 400.99591653, 668.65446791,
       520.89586333, 303.13513252, 196.41253332, 289.563102  ,
       470.82152486, 385.32656939, 416.79065469, 462.89000381,
       512.97103636, 340.40009995, 711.11319687, 350.5805105 ,
       465.13531008, 496.75542764, 265.3611899 , 460.0690688 ,
       420.45095812, 437.07665478, 488.37097522, 209.40265799,
       407.68879099, 333.79112926, 582.18715586, 405.42896638,
       502.74367959, 582.87987905, 423.49036255, 523.48471129,
       416.0051862 , 379.4029117 , 397.30079169, 540.7358417 ,
       487.18156965, 457.90486137, 462.6479807 , 359.18694896,
       317.01577373, 145.33635966, 684.51134516, 321.96081218,
       510.26362124, 421.83302834, 528.77246408, 332.84465802,
       447.69693267, 416.84085921, 377.90889561, 275.46840462,
       364.60663042, 558.87324612, 395.04846104, 339.31092994,
       618.44935625, 268.7959028 , 388.6608158 , 440.71172803,
       398.97729555, 400.59526509, 196.42231107, 353.35094428,
       576.37446715, 207.37255628, 369.89123527, 261.00220119,
       393.93640276, 409.14536366, 103.83983735, 279.25147032,
       453.17963919, 492.05500965, 475.60253352, 427.43236293,
       486.60369979, 612.13948861, 304.81123108, 293.09411183,
       551.90535916, 312.15919186, 599.29088898, 471.82870142,
       375.75198462, 284.16988905, 605.26776466, 590.20273157,
       427.53635712, 467.49774464, 576.92092547, 498.47273616,
       502.99785894, 474.77015804, 346.1184067 , 448.5371006 ,
       391.39334551, 266.2917157 , 489.59779797, 517.6399771 ,
       527.71619138, 254.14267163, 449.18907255, 474.40117305,
       245.05399473, 733.23118664, 397.98045974, 463.46234035,
       372.16044548, 442.89250349, 289.41408252, 445.03374083,
       501.30526418, 454.43741893, 391.10793275, 399.73330778,
       450.10376613, 297.87101653, 449.15609696, 544.73490721,
       453.57020994, 244.00307319, 271.11658246, 430.76405505,
       296.71523027, 294.27690684, 366.87406111, 418.72888453,
       476.62315644, 267.20487647, 446.15109173, 382.54364241,
       436.96925001, 310.20608596, 399.43274411, 380.11545981,
       314.89144519, 410.3240601 , 260.30144031, 411.98346333,
       514.27107296, 496.07419094, 395.81338802, 395.38853958,
       362.13193553, 568.87994072, 402.66344074, 430.21496587,
       290.56060694, 631.88365732, 268.76201601, 402.65709781,
       420.99609103, 502.1996864 , 366.18002455, 362.0318124 ,
       513.95332117, 545.7471529 , 390.98697458, 464.19513138,
       665.03955298, 518.00788134, 419.9526842 , 283.70444263,
       265.41236847, 367.50146238, 581.24529328, 396.20330572,
       466.77730318, 212.58134585, 455.08663405, 712.42277367,
       554.25508932, 310.05046388, 420.74520654, 201.98852031,
       395.77804352, 388.04241537, 565.24936886, 293.06005636,
       254.19412154, 334.39510091, 450.38958216, 449.8601399 ,
       354.86809244, 388.82137638, 522.91815171, 500.38562302,
       470.42706753, 364.38121144, 296.20164832, 163.00021489,
       513.78734711, 530.51085277, 582.54272723, 318.84707593,
       435.23462261, 219.37349741, 470.8815763 , 612.78205618,
       447.30779221, 346.71985856, 370.31746287, 437.42606153,
       367.10711066, 287.54414025, 357.26660766, 286.87624845,
       601.1573611 , 480.5107072 , 444.09179257, 422.08009112,
       404.73867161, 519.93876787, 576.09605112, 326.34612684,
       423.58792053, 496.1964304 , 356.45525793, 449.15278758,
       435.82886599, 285.51899538, 468.7736881 , 362.42705426,
       403.59783351, 572.02719862, 455.89010063, 521.09652009,
       499.39548045, 339.4036308 , 330.09676504, 301.24596672,
       319.18379066, 494.41372837, 397.69176946, 320.85732086,
       480.92094117, 284.87714392, 482.0588706 , 510.67752474,
       122.65836509, 307.38091317, 259.53119181, 297.64426816,
       297.20165103, 295.06872985, 450.92448588, 250.81885603,
       506.85858181, 313.80870184, 411.5180209 , 483.04366861,
       491.43639383, 321.29734852, 354.74007831, 524.93917303,
       662.31560879, 366.09460652, 413.10262841, 511.96663638,
       641.20177307, 671.42979127, 411.73293202, 415.00146823,
       377.40237424, 366.75275096, 442.46968406, 380.05946469,
       459.05395361, 244.44715987, 149.29165826, 457.14031388,
       421.00875672, 337.20252149, 326.34075165, 519.8978321 ,
       488.14033814, 264.84924446, 452.05903665, 590.89549086,
       373.93061708, 403.54072794, 305.13558161, 234.33917634,
       402.54703272, 469.51867571, 336.03361148, 631.37267645,
       400.12066077, 326.29516916, 517.10849623, 434.59121403,
       357.15406226, 631.29556744, 279.19703497, 417.33697912,
       450.70451512, 269.01381176, 369.69609984, 267.74684292,
       550.33906948, 357.35625211, 409.43321314, 351.01173727,
       436.6657415 , 322.52529591, 312.67866487, 511.47703089,
       393.63357213, 500.9083713 , 246.91398462, 392.81709848,
       402.61688344, 326.61004221, 395.01797495, 519.7172868 ,
       417.79531292, 480.17126122, 216.4476712 , 584.63518513,
       289.94209429, 333.61536522, 362.56321195, 454.43167516,
       520.44147748, 494.03859673, 407.26534303, 516.6116819 ,
       357.47088488, 350.85074533, 455.88942874, 506.40668195,
       530.96280728, 409.05957183, 322.28778419, 348.74171306,
       436.46952349, 318.5750119 , 389.93729305, 572.06000726,
       319.28048804, 467.83207055, 420.46699588, 605.44934785,
       510.92024341, 522.83898801, 563.83613949, 489.90614849,
       470.57969553, 431.92180015, 397.22741466, 246.37148321,
       439.81315103, 354.43010502, 364.34508942, 422.09231608,
       227.00009442, 608.64928778, 308.87065293, 462.95993886,
       526.7390816 , 449.73812781, 591.78097611, 407.26862864,
       392.85990703, 476.63186814, 418.3139943 , 292.3033134 ,
       433.8350755 , 462.57077595, 461.1032753 , 318.77738576,
       370.9571666 , 247.47656936, 435.94708409, 376.02347258,
       346.48750012, 324.43585928, 393.17733727, 507.55421513,
       465.41034426, 345.14795518, 492.98878246, 581.6486576 ,
       388.12100624, 255.96061126, 378.370788  , 448.90355654,
       550.46408713, 338.60301199, 471.29896692, 352.01912548,
       374.09101468, 340.47929057, 385.79195187, 347.19300576,
       568.58960305, 606.11562658, 327.21266784, 460.14073734,
       469.49807405, 213.73855879, 598.0053482 , 446.74604365,
       289.70000307, 420.66295915, 443.7594403 , 466.43773697,
       371.1405848 , 524.05243458, 373.24981674, 376.09719324,
       179.61987526, 283.33035292, 551.16967483, 387.25880017,
       467.01743309, 571.88932733, 443.0320904 , 374.665837  ,
       367.3913197 , 411.75843675, 486.60538264, 225.11099737,
       520.22717506, 340.20618236, 503.18431258, 421.13015005,
       543.71457216, 325.49164039, 450.07849761, 601.29835072,
       591.21828882, 354.15254812, 350.07553485, 325.95739936,
       315.26923411, 324.12253995, 312.4594466 , 476.75172174,
       353.63296487, 427.90883953, 497.4806071 , 323.14190877])

How about we try to compare the different types of pokemon? In the cell below, list the types of Pokemon from column `Type 1` and the count of each type.

In [15]:
# Your code here:
pokemon["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

Since water is the largest group of Pokemon, compare the mean and standard deviation of water Pokemon to all other Pokemon.

In [16]:
# Your code here:

mean_type = pokemon.groupby("Type 1")["Total"].mean().sort_values(ascending = False)

Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon. Assume the variances are equal.

In [17]:
# Your code here:

std_type = pokemon.groupby("Type 1")["Total"].std().sort_values(ascending = False)

Write your conclusion below.

In [18]:
# Your conclusions here:

# Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon.
# Assume the variances are equal.

pd.DataFrame({'mean': mean_type, 'std': std_type})

                mean         std
Type 1
Bug       378.927536  117.875223
Dark      445.741935  109.126217
Dragon    550.531250  146.267538
Electric  443.409091  105.721952
Fairy     413.176471  123.781680
Fighting  416.444444  102.464378
Fire      458.076923  109.760496
Flying    485.000000  161.400124
Ghost     439.562500  110.072685
Grass     421.142857  106.650626
Ground    437.500000  123.913081
Ice       433.458333  108.281027
Normal    401.683673  115.733038
Poison    399.142857   92.358687
Psychic   475.947368  139.026645
Rock      453.750000  108.059227
Steel     487.703704  115.420907
Water     430.455357  113.188266

# Challenge 2 - Matched Pairs Test

In this challenge we will compare dependent samples of data describing our Pokemon. Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. In the cell below, import the `ttest_rel` function from `scipy.stats` and compare the two columns to see if there is a statistically significant difference between them.

In [11]:
# Your code here:

Describe the results of the test in the cell below.

In [12]:
# Your conclusions here:

We are also curious about whether therer is a significant difference between the mean of special defense and the mean of special attack. Perform the hypothesis test in the cell below.

In [13]:
# Your code here:

Describe the results of the test in the cell below.

In [14]:
# Your conclusions here:

As you may recall, a two sample matched pairs test can also be expressed as a one sample test of the difference between the two dependent columns.

Import the `ttest_1samp` function and perform a one sample t-test of the difference between defense and attack. Test the hypothesis that the difference between the means is zero. Confirm that the results of the test are the same.

In [16]:
# Your code here:

# Bonus Challenge - The Chi-Square Test

The Chi-Square test is used to determine whether there is a statistically significant difference in frequencies. In other words, we are testing whether there is a relationship between categorical variables or rather when the variables are independent. This test is an alternative to Fisher's exact test and is used in scenarios where sample sizes are larger. However, with a large enough sample size, both tests produce similar results. Read more about the Chi Squared test [here](https://en.wikipedia.org/wiki/Chi-squared_test).

In the cell below, create a contingency table using `pd.crosstab` comparing whether a Pokemon is legenadary or not and whether the Type 1 of a Pokemon is water or not.

In [17]:
# Your code here:

Perform a chi-squared test using the `chi2_contingency` function in `scipy.stats`. You can read the documentation of the function [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html).

In [18]:
# Your code here:

Based on a 95% confidence, should we reject the null hypothesis?

In [19]:
# Your answer here: